### ISSUE TITLE
how to use this with a message bus?

### ISSUE THREAD

**Issue by vesper8** [jeffreyguenther/vue-turbolinks#19] opened 2017-12-24 13:44 UTC
I've been using this for a few weeks and all works well, but there was this one problem that was really stumping me

Tonight I spent an hour debugging it and found out what was happening.

In my vue application I use a message bus. So in a few places I have these ```Bus.$on('this_and_that')``` listeners and in other parts of my app I have ```Bus.$emit('this_and_that')```. I have dozens of these scattered through my app.

I was noticing that using turbolinks and vue-turbolinks, everytime I would visit a new page.. anything emitted to one of my Bus listeners would fire 2, 3, 4 etc times.. everytime I loaded a new page it would fire these events one extra time

In retrospect I see this makes sense.. although **I thought I read somewhere that when the Vue teardown occurred the listeners were destroyed**? not in my case I guess

I really struggled to find the correct way to prevent this from happening. I needed something that was the opposite of turbolinks:load. I wanted to attach the ```Bus.$on``` listeners only the first time my vue app was loaded (I have the same vue app on every page of my site)

I couldn't figure it out so I hacked something up. I simply used vuex to store the number of "page loads" which is initialized to 0, then on one of my top components in a beforeDestroy hook I increment the pageLoads state in the vuex store

And finally, I wrapped my ```Bus.$on``` calls with ```if(this.pageLoads === 0) { ... } ``` so it only happens on the very first load

This is suuper ugly.. and worse I had to wrap like 25 ```Bus.$on``` calls with this ugliness

**What am I doing wrong here?? what was I supposed to do?**

**Comment by jeffreyguenther** [comment] 2018-02-13 21:04
Great question! 😄I think the key is to figure out if the Vue teardown is actually happening. Based on what you're reporting it might not be.

**Comment by jeffreyguenther** [comment] 2018-02-26 21:22
@vesper8 have you made any progress solving this problem? 

This plugin works best when component initialization is idempotent. With Turbolinks a page is never destroyed. Its body is replaced in the background. As a result, each time you load your component, you are adding the bus listeners. You can use the Turbolinks `before-cache` or `visit` events to clean up before the page changes. What you need is similar to what this plugin does for Vue components. It resets the DOM back to its initial state so that on [restoration visits](https://github.com/turbolinks/turbolinks#restoration-visits) the DOM is as the component expects.

I'm going to close this for now as this plugin is working as intended.

**Closed as completed by jeffreyguenther** 2018-02-26 21:22 UTC

**Comment by vesper8** [comment] 2018-02-27 07:11
Hey @jeffreyguenther 

I've added this to my main component (the one that encapsulates all others)

```
        beforeDestroy() {
            Bus.$off();
        },
```

And that seems to have made that problem go away

However I've been having another more serious problem which has required me have to disable turbolinks altogether for now.. it's kind of an edge case but maybe you can help me understand an easy workaround

I make heavy use of https://github.com/matfish2/vue-tables-2 in my application. On nearly every page.

I use a feature of that package called "custom templates" which is where you are allowed to specify your own template to be used for the rendering of the whole data table which has a lot of customization options

You specify this inside of the Vue.use() call

```
import {ServerTable} from "vue-tables-2";
Vue.use(ServerTable, {}, true, require('components/template-uncompiled-bare.js')('server'));
```

I use different custom templates on different pages

The problem I've had with turbolinks from day one is that whichever is the first custom template to be declared, is the one that persists when users change to other pages that require a different template to be rendered properly

So the result is I have broken layouts on pages other than the one the user first visits

I've opened some issues about it https://github.com/matfish2/vue-tables-2/issues/433

And it seems there's no easy way around the problem on their side.. 

But maybe you had the answer all along.. I just need to fully tear down this table and recreate it from scratch.. right? So how do I do that? How do a I tear down the Vue.use() statement?

some assistance resolving this important issue for my project would be so helpful!! thanks!

**Comment by jeffreyguenther** [comment] 2018-02-27 19:28
You want to handle the appropriate [Turbolinks lifecycle event ](https://github.com/turbolinks/turbolinks#full-list-of-events) to reload your template. Most likely you're looking for `turbolinks:load`. Anything you need to happen each time the page is rendered goes in that event. It's analogous to the DOMContentLoaded event.

Turbolinks is a tricky beast as it changes the lifecycle of a normal HTML page and changes many of the assumptions we make about how things will happen. If you haven't read the Turbolinks docs completely, I recommend doing that because it can be a mind bender at times.
